void array_to_poly(uint16_t* in, poly* out);
void poly_to_array(uint16_t* out, const poly* in);
void array_aleatorio(uint16_t* ar);
void array_aleatorio_r(uint16_t* ar);
void array_mult(uint16_t* e, const uint16_t* r, const uint16_t* h, int DBG);
void array_mult_v16bits(uint16_t* e, const uint16_t* r, const uint16_t* h, int DBG);
void sleep_pynq_ms(int ms);
int comprobar_igualdad(const poly* poly_e, const uint16_t* e);
int comprobar_igualdad_c(const unsigned char* c, const unsigned char* c_libntru);
void array_aleatorio_dr(uint16_t* ar, int dr, int DBG);
void array_aleatorio_dr_rapido(uint16_t* ar, int dr, int DBG);
void num_ones_minus(uint16_t* ar, int DBG);
void num_ones_minus_exit(uint16_t* ar, int* ar_exit, int DBG);
int comprobar_igualdad_crypto(const unsigned char* ss, const unsigned char* ss_dec);